package hu.dpc.edu.userGUI;

import hu.dpc.edu.User;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;

/**
 * Created by vrg on 11/10/16.
 */
public class UserFrame extends JFrame {

    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTable usersTable;

    /**
     * Creates new form Test
     */
    public UserFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        panel = new javax.swing.JPanel();
        userNameField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        usersTable = createUsersTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        setTitle("User Manager");

        firstNameField.setToolTipText("");

        lastNameField.setToolTipText("");

        saveButton.setText("Save");
        //TODO ADD ACTION LISTENER HERE
        saveButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                saveUser(User.builder()
                        .username(userNameField.getText())
                        .firstName(firstNameField.getText())
                        .lastName(lastNameField.getText())
                        .build());
                //tableModel.changed();
            }

        });

        deleteButton.setText("Delete");

        usernameLabel.setText("Username");

        firstNameLabel.setText("First name");

        lastNameLabel.setText("Last name");

        scrollPane.setViewportView(usersTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(panel);
        panel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .
                addGroup(jPanel1Layout.createSequentialGroup()
                        .
                        addGap(0, 268, Short.MAX_VALUE)
                        .
                        addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .
                                addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .
                                        addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .
                                                addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .
                                                        addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .
                                                                addComponent(firstNameLabel)
                                                                .
                                                                addComponent(lastNameLabel))
                                                        .
                                                        addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .
                                                        addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .
                                                                addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .
                                                                addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .
                                                addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .
                                                        addComponent(usernameLabel)
                                                        .
                                                        addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .
                                                        addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .
                                        addContainerGap())
                                .
                                addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .
                                        addComponent(deleteButton)
                                        .
                                        addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .
                                        addComponent(saveButton))))
                .
                addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .
                        addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .
                                addContainerGap()
                                .
                                addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                .
                                addGap(264, 264, 264)))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .
                addGroup(jPanel1Layout.createSequentialGroup()
                        .
                        addContainerGap()
                        .
                        addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .
                                addComponent(userNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .
                                addComponent(usernameLabel))
                        .
                        addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .
                        addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .
                                addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .
                                addComponent(firstNameLabel))
                        .
                        addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .
                        addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .
                                addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .
                                addComponent(lastNameLabel))
                        .
                        addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                        .
                        addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .
                                addComponent(saveButton)
                                .
                                addComponent(deleteButton))
                        .
                        addContainerGap())
                .
                addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .
                        addGroup(jPanel1Layout.createSequentialGroup()
                                .
                                addContainerGap()
                                .
                                addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                .
                                addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());

        getContentPane().
                setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .
                addGroup(layout.createSequentialGroup()
                        .
                        addContainerGap()
                        .
                        addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .
                        addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .
                addGroup(layout.createSequentialGroup()
                        .
                        addGap(6, 6, 6)
                        .
                        addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .
                        addGap(6, 6, 6))
        );

        pack();

    }

    private static JTable createUsersTable() {
        //TODO create JTable with a new tablemodel
        return new javax.swing.JTable(new DefaultTableModel(new String[]{
            "Username", "first name", "last name"}, 3));
    }

    private void saveUser(User build) {
        //TODO save the user here
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }

}
